### PR TITLE
Expand the external table support

### PR DESCRIPTION
**Pull request by msgongora**
* allow provider version 5.0 which implements more recent features from bigquery and also fix some bugs related to external tables.
* add connectionId field required by external sources such as Azure Blob, Cloud Storage, or S3.
* add support parquet and avro options.
* add support to metadataCacheMode.
* add support to maxStaleness for regular and external tables.
* set schema as optional for external tables.

### CODE REVIEW

**Review by dlesco — CHANGES_REQUESTED** [review]
The README.md documents all inputs; so it should be updated as well so it's not inconsistent.

**Review by dlesco — CHANGES_REQUESTED** [review]
We must add support for the terraform `hive_partitioning_options` block.  Using external tables with big data is crippled without this support.  Related documentation:

https://cloud.google.com/bigquery/docs/hive-partitioned-queries

**Comment by dlesco** [comment]
> We must add support for the terraform `hive_partitioning_options` block. Using external tables with big data is crippled without this support. Related documentation:

Actually, I already see that option listed in the README.md, so it may already be supported by tf-mod-bq.

**Comment by msgongora** [comment]
> We must add support for the terraform `hive_partitioning_options` block. Using external tables with big data is crippled without this support. Related documentation:
> 
> https://cloud.google.com/bigquery/docs/hive-partitioned-queries

the support for `hive_partitioning` is already here thanks to upstream: https://github.com/cbsi-dto/tf-mod-bq/blob/702c453ac91bcf65a0e1610ed1bfdf715e6a8923/variables.tf#L212-L215

**Review by dlesco — APPROVED** [review]

**Pull request merged**
